In [1]:
#Que no - 1 

In [3]:
#A Python library is a collection of pre-written code that developers can reuse in their programs to solve specific
#tasks or implement functionalities. Python libraries often contain modules, functions, and classes that provide useful tools, 
#so you don’t have to write code from scratch.

In [4]:
#Que no - 2

In [8]:
#Difference between numpy array and list are given below-

#1- Array contains only one datatype while list can contain values from different data types.
#2- Arrays are faster than list.
#3- Array takes less memory compare to list.
#4- Array Supports different types of scientific calculation which lists do not support.

In [9]:
#Que no - 3

In [16]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr.shape

(3, 4)

In [18]:
arr.size

12

In [23]:
arr.ndim

2

In [24]:
#Que no - 4

In [28]:
for i in range(len(arr[0])):
    print(arr[0][i], end=", ")

1, 2, 3, 4, 

In [29]:
#Que no - 5

In [31]:
arr[2][3]

12

In [32]:
#Que no - 6

In [39]:
arrShape = list(arr.shape)
for i in range(arrShape[0]):
    for j in range(arrShape[1]):
        if (i==1 and j==1) or (i%2!=0 and j%2!=0):
            print(arr[i][j])

6
8


In [40]:
#Que no - 7

In [42]:
np.random.rand(3, 3)

array([[0.30042758, 0.83265914, 0.41881446],
       [0.32732303, 0.71969488, 0.0242409 ],
       [0.7966846 , 0.77204236, 0.00534074]])

In [43]:
#Que no - 8

In [44]:
#np.random.rand() generates numbers between 0 and 1 from a uniform distribution.
#np.random.randn() generates numbers from a standard normal distribution (mean = 0, standard deviation = 1).

In [45]:
#Que no - 9

In [46]:
arr.ndim

2

In [50]:
arr2 = np.expand_dims(arr, axis=0)

In [51]:
arr2.ndim

3

In [52]:
#Que no - 10

In [54]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
#Que no - 11

In [75]:
a = np.matrix([[1,2,3],[5,6,7],[9,10,11]])
b = np.matrix([[1,2,3],[5,6,7],[9,10,11]])

In [76]:
a*b

matrix([[ 38,  44,  50],
        [ 98, 116, 134],
        [158, 188, 218]])

In [80]:
a @ b

matrix([[ 38,  44,  50],
        [ 98, 116, 134],
        [158, 188, 218]])

In [81]:
a + b

matrix([[ 2,  4,  6],
        [10, 12, 14],
        [18, 20, 22]])

In [82]:
b - a

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [83]:
b//a

matrix([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [87]:
#Que no - 12

In [85]:
arr.byteswap()

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

In [88]:
#Que no - 13

In [89]:
#The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.

In [90]:
#Que no - 14

In [92]:
#reshape function of numpy, shapes an array into desired dimentions, the multiplication of the original shape of array
#should be same as the multiplication of desired array shape.

In [93]:
arr.shape

(3, 4)

In [94]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [95]:
#Que no - 15

In [96]:
#Broadcasting is a fundamental feature in NumPy that enables flexible and efficient arithmetic operations on arrays of different shapes.